[variables]
NODE_ENV = "development"

[phases.install]
cmds = ["rm -rf node_modules && npm install --legacy-peer-deps --include=dev"]

[phases.build]
cmds = ["node_modules/.bin/prisma generate"]

[start]
cmd = "node_modules/.bin/prisma migrate deploy && node server.js"