/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */
import * as React from 'react';
export const projectId = "rwtyktmtzomrfzbgqydr"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3dHlrdG10em9tcmZ6YmdxeWRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMzMjc1MzEsImV4cCI6MjA4ODkwMzUzMX0.5PSa7IHydJxAoMGq3uuhrGwXLcb6Y2IL_xIbp58_n7M"